/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface MessagePayload {
  message: string
}
export interface NodePayload {
  id: number
  serial: number
  nick?: string
  name?: string
  description?: string
}
export interface LinkPayload {
  id: number
  serial: number
  inputPortId: number
  outputPortId: number
  inputNodeId: number
  outputNodeId: number
}
export interface PortPayload {
  id: number
  serial: number
  nodeId: number
  secondaryId: number
  formatDsp?: string
  audioChannel?: string
  name?: string
  direction?: string
}
export interface IdPayload {
  id: number
}
export interface EventWrapper {
  eventName: string
  payload: string
}
/** Initialize PipeWire listener with callback */
export declare function init(callback: (event: EventWrapper) => void): void
/** Hello world function */
export declare function hello(name: string): string
