// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface LinkPayload { id: number, serial: number, input_port_id: number, output_port_id: number, input_node_id: number, output_node_id: number, }