// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface PortPayload { id: number, serial: number, node_id: number, secondary_id: number, format_dsp: string | null, audio_channel: string | null, name: string | null, direction: string | null, }